 
instance_dir:  # the path for dataset image

target_dir:  # the output path for perturbed image

CAAT: 
  dir_suffix: ~
  img_prefix: ~

ANTIDB: 
  dir_suffix: ~
  img_prefix: ~

ADVDM: 
  dir_suffix: ~
  img_prefix: ~

METACLOAK: 
  dir_suffix: ~
  img_prefix: ~
