 
instance_dir: ~ # the path for image to be evaluated

output_dir: ~  # the output dir for evaluation result, the results file will be named by the instance_dir

prompt: ~ # the input prompt for generation

CelebA-HQ:
  id_emb_path: ~ 
VGGFace2:
  id_emb_path: ~

CAAT: 
  dir_suffix: 250/
  img_prefix: 250_noise_

ANTIDB: 
  dir_suffix: ~
  img_prefix: ~

ADVDM: 
  dir_suffix: ~
  img_prefix: ~

METACLOAK: 
  dir_suffix: ~
  img_prefix: ~
