
seed: 1042

message_length: 32

message_dir: ~ # the path for image with authorization perturbation

target_dir: ~  # the output path for perturbed image

method: CAAT

dataset: CelebA-HQ

CAAT: 
  dir_suffix: 250
  img_prefix: 250_noise_

ANTIDB: 
  dir_suffix: ~
  img_prefix: ~

ADVDM: 
  dir_suffix: ~
  img_prefix: ~

METACLOAK: 
  dir_suffix: ~
  img_prefix: ~
