
seed: 1042

message_length: 32

message_dir: ~ # the path for image with authorization perturbation

target_dir: ~  # the output path for perturbed image

method: CAAT

dataset: CelebA-HQ

CAAT: 
  dir_suffix: 250/
  img_prefix: 250_noise_

ANTIDB: 
  dir_suffix: noise-ckpt/50/
  img_prefix: 50_noise_

ADVDM: 
  dir_suffix: ''
  img_prefix: noise_

METACLOAK: 
  dir_suffix: noise-ckpt/final/
  img_prefix: noisy_